# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Vungle Sample App Swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vungle Sample App Swift

    pod "VungleSDK-iOS", "5.1.0"

end
